.TH "pila.cpp" 3 "Miércoles, 24 de Octubre de 2018" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pila.cpp \- Fichero implementación métodos del TDA \fBPila\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br

.SH "Descripción detallada"
.PP 
Fichero implementación métodos del TDA \fBPila\fP\&. 


.PP
\fBAutor:\fP
.RS 4
Jose Antonio Padial Molina 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
