.TH "pila.h" 3 "Miércoles, 24 de Octubre de 2018" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pila.h \- Fichero cabecera del TDA \fBPila\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include 'pila\&.cpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPila< T >\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBPila\fP\&. 


.PP
\fBAutor:\fP
.RS 4
Jose Antonio Padial Molina
.RE
.PP
Gestiona una secuencia de elementos con funcionamiento de pila a través de un tipo de dato List de la STL\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
