.TH "usopila.cpp" 3 "Miércoles, 24 de Octubre de 2018" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usopila.cpp \- Fichero ejemplo de uso de la implementación del TDA \fBPila\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'pila\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Fichero ejemplo de uso de la implementación del TDA \fBPila\fP\&. 


.PP
\fBAutor:\fP
.RS 4
Jose Antonio Padial Molina 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
